# USE NODE JS WITH SMALL LINUX DISTRIBUTION ALPINE 
FROM node:alpine

# COPY ALL THE FILE AND DIRECTORY INTO THE APP DIRECTOR
COPY . /app 

# WE CAN SET OUR DEFAULT DIRECTORY TO /APP WHICH HAS ALL THE FILES 
# ALTERNATIVELY WE HAVE TO USE "CMD node /app/app.js"
WORKDIR /app

# RUN NODE APPLICATION WITH COMMAND - APP.JS IS NOW INSIDE APP FOLDER
CMD node /app.js